In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
fj = pd.read_csv(r"C:\Users\YASH\OneDrive\Desktop\Classes Study Material\Streamlit Projects\Fake_job_posting\fake_job_postings.csv")
fj.head(1)

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0

In [5]:
fj.shape

(17880, 18)

In [6]:
fj.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17880 non-null  int64
 1   title                17880 non-null  object
 2   location             17534 non-null  object
 3   department           6333 non-null   object
 4   salary_range         2868 non-null   object
 5   company_profile      14572 non-null  object
 6   description          17879 non-null  object
 7   requirements         15184 non-null  object
 8   benefits             10668 non-null  object
 9   telecommuting        17880 non-null  int64
 10  has_company_logo     17880 non-null  int64
 11  has_questions        17880 non-null  int64
 12  employment_type      14409 non-null  object
 13  required_experience  10830 non-null  object
 14  required_education   9775 non-null   object
 15  industry             12977 non-null  object
 16  function             11425 non-null  object
 17  fraudulent           17880 non-null  int64
dtypes: int64(5), object(13)
memory usage: 2.5+ MB

In [8]:
fj.isnull().sum()

job_id                     0
title                      0
location                 346
department             11547
salary_range           15012
company_profile         3308
description                1
requirements            2696
benefits                7212
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         3471
required_experience     7050
required_education      8105
industry                4903
function                6455
fraudulent                 0
dtype: int64

In [9]:
text_columns = ["title", "company_profile","description","requirements","benefits"]

In [10]:
for col in text_columns:
    fj[col] = fj[col].fillna("")

In [11]:
fj["text"] = (fj["title"] + " " + fj["company_profile"] + " " + fj["description"] + " " + fj["requirements"] + " " + fj["benefits"])

In [12]:
fj[["text", "fraudulent"]].head()

                                                text  fraudulent
0  Marketing Intern We're Food52, and we've creat...           0
1  Customer Service - Cloud Video Production 90 S...           0
2  Commissioning Machinery Assistant (CMA) Valor ...           0
3  Account Executive - Washington DC Our passion ...           0
4  Bill Review Manager SpotSource Solutions LLC i...           0

In [13]:
X = fj["text"]
Y = fj["fraudulent"]

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=.2, random_state=1234, stratify= Y)
print("Training data :", X_train.shape)
print("Test data :", X_test.shape)

Training data : (14304,)
Test data : (3576,)

In [16]:
vectorizer = TfidfVectorizer(max_features=10000, stop_words="english")

In [17]:
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)
print(X_train_tfidf.shape)

(14304, 10000)

In [21]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000, random_state=1234, class_weight='balanced')
lr.fit(X_train_tfidf, Y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=1234)

In [22]:
Y_pred = lr.predict(X_test_tfidf)
print("Accuracy:", accuracy_score(Y_test, Y_pred))

Accuracy: 0.9723154362416108

In [23]:
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      3403
           1       0.67      0.86      0.75       173

    accuracy                           0.97      3576
   macro avg       0.83      0.92      0.87      3576
weighted avg       0.98      0.97      0.97      3576

In [26]:
import pickle

with open("fake_job_model.pkl", "wb") as file:
    pickle.dump(lr, file)

with open("tfidf_vectorizer.pkl", "wb") as file:
    pickle.dump(vectorizer, file)

print("Model saved successfully!")
print("Vectorizer saved successfully!")

Model saved successfully!
Vectorizer saved successfully!

In [24]:
pwd

'C:\\Users\\YASH'